#!/usr/bin/bash

# 1) ejecutar desde la linea de comandos:
# bash run-tests
# 2) si el comando anterior pide permisos de ejecucion ejecute el siguiente comando 
#    y despues repita al paso 1
# chmod +rwx run-tests
# *posiblemente el ejecutable chktex, necesite permisos de ejecucion;
#  en caso de necesitar, ejecute: chmod +rwx chktex

PASS="Test: \e[1;32mSUCCESS!\e[0m"
FAIL="Test: \e[1;31mFAILURE!\e[0m"
pass_counter=""
fail_counter=""

folders_one_compilation=(plain-text emphasis-text headers numbered-headers pagenumbering simple-figures \
       multiple-figures cover-default cover-report tables tables-csv lists)

folders_two_compilation=(table-of-contents list-of-figures list-of-tables bibliography)

pass_counter=$((0))
fail_counter=$((0))

#echo "paquetes LaTeX requeridos por md2tex..."
#if ./chktex $1; then
#    echo "todos los paquetes requeridos estan instalados en su sistema..."
#else
#    echo -e "para instalar los paquetes faltantes, ejecute: \e[1;33mtlmgr install <package>\e[0m o configure los paquetes manualmente"
#fi
sleep 1

# tests que requieren solo una compilacion
for folder in "${folders_one_compilation[@]}"; do
    echo -e "\n"
    echo "TEST: $folder"
    echo -e "\e[1;33m----------------------------------\e[0m"
    echo "Copiando md2tex en el folder $folder..."
    cp md2tex $folder/
    echo "Entrando a folder $folder..."
    cd $folder
    echo "Ejecutando md2tex..."
    if ./md2tex $folder.md; then
        echo -e "\e[1;32mmd2tex se ejecuto sin errores...\e[0m"
    else
        echo -e "\e[1;31mmd2tex se ejecuto con errores...\e[0m"
    fi
    echo "Eliminando md2tex de $folder..."
    rm md2tex

    echo "Ejecutando pdfLaTeX..."
    cd latex/tex
    mkdir -p output
    if pdflatex --interaction=batchmode --output-directory=output $folder.tex; then
        echo -e $PASS
        pass_counter=$((pass_counter+1))
    else
        echo -e $FAIL
        fail_counter=$((fail_counter+1))
    fi
    cd ../../../
    sleep 1
done

# tests que requieren dos compilaciones
for folder in "${folders_two_compilation[@]}"; do
    echo -e "\n"
    echo "TEST: $folder"
    echo -e "\e[1;33m----------------------------------\e[0m"
    echo "Copiando md2tex en el folder $folder..."
    cp md2tex $folder/
    echo "Entrando a folder $folder..."
    cd $folder
    echo "Ejecutando md2tex..."
    if ./md2tex $folder.md; then
        echo -e "\e[1;32mmd2tex se ejecuto sin errores...\e[0m"
    else
        echo -e "\e[1;31mmd2tex se ejecuto con errores...\e[0m"
    fi
    echo "Eliminando md2tex de $folder..."
    rm md2tex

    echo "Ejecutando pdfLaTeX..."
    cd latex/tex
    mkdir -p output
    # para crear archivos auxiliares: toc, lof, lot...
    pdflatex --interaction=batchmode --output-directory=output $folder.tex

    # para ejecutar biber
    if [ $folder == "bibliography" ]; then
        biber $folder --onlylog --output-directory output
    fi

    if pdflatex --interaction=batchmode --output-directory=output $folder.tex; then
        echo -e $PASS
        pass_counter=$((pass_counter+1))
    else
        echo -e $FAIL
        fail_counter=$((fail_counter+1))
    fi
    cd ../../../
    sleep 1
done

echo -e "\e[1;33m-----------------------\e[0m"
echo -e "Tests Passed: \e[1;33m" $pass_counter "\e[0m"
echo -e "Tests Failed: \e[1;33m" $fail_counter "\e[0m"
echo -e "\e[1;33m-----------------------\e[0m"
